version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'azerty@123'
      MYSQL_DATABASE: autoloc_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_gui
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "80:80"

volumes:
  db_data:
